### ISSUE TITLE
Unable to disable plugin

### ISSUE THREAD

**Issue by matthewsia98** [python-lsp/python-lsp-ruff#11]
Setting enabled key here does not affect anything.
However, setting ignore key causes ruff to ignore the specified key.

pylsp settings
```
    local lspconfig = require("lspconfig")
    lspconfig["pylsp"].setup({
        settings = {
            pylsp = {
                plugins = {
                    ruff = {
                        enabled = false,
                        ignore = {
                            "E741",
                        },
                    },
                },
            },
        },
```

Without ignore key
![image](https://user-images.githubusercontent.com/71731492/211165887-6fecf877-e8c6-40aa-b632-1f2146b05b75.png)

With ignore key
![image](https://user-images.githubusercontent.com/71731492/211165925-dd136bce-4510-43ea-88bb-63ba03397b2f.png)

**Comment by jhossbach** [comment]
Hmm, this is odd indeed, I can reproduce this issue even when setting
```python
@hookimpl
def pylsp_settings():
    return {
        "plugins": {
            "ruff": {
                "enabled": False,
            },
        }
    }
in the package itself. Do you have any idea @ccordoba12 ?

```

**Comment by ccordoba12** [comment]
I check this and (I don't know why), third-party plugins can only be disabled by passing their module names. So, the above configuration should be:

```
    local lspconfig = require("lspconfig")
    lspconfig["pylsp"].setup({
        settings = {
            pylsp = {
                plugins = {
                    pylsp_ruff = {
                        enabled = false,
                    },
                    ruff = {
                        ignore = {
                            "E741",
                        },
                    },
                },
            },
        },
```

That works for me in Spyder.

**Comment by jhossbach** [comment]
Thanks for the help @ccordoba12! I'd rather stick to 1. to keep the plugin configurations consistent. Unfortunately I am unfamiliar with `pluggy`, changing the pyproject.toml in you code snippet to
```python
[project.entry-points.pylsp]
ruff = "pylsp_ruff.ruff_lint"
```
doesn't fix it on my side. Am I missing something?

**Comment by ccordoba12** [comment]
> Am I missing something?

Yes, changing the name is not enough. Afterwards, you need to uninstall the plugin and reinstall it again in development mode for the change to take effect.

I tested this locally and it works for me with Spyder, so I'll submit a PR for it.

**Comment by jhossbach** [comment]
Right, that was it. Thanks for the help!
