### ISSUE TITLE
Please add this package to conda forge

### ISSUE THREAD

**Issue by felixgwilliams** [python-lsp/python-lsp-ruff#15]
Thank you all for this package. I find it very useful for linting code in jupyter notebooks via `jupyterlab-lsp`.

As a conda user, I would find it useful if the package was available to install with conda, not just pip.

Thanks again!

**Comment by jhossbach** [comment]
Python-lsp-ruff is now available via conda-forge, closed with https://github.com/conda-forge/staged-recipes/pull/22139
