### ISSUE TITLE
Avoiding passing `pyproject.toml` options as command-line arguments

### ISSUE THREAD

**Issue by charliermarsh** [python-lsp/python-lsp-ruff#2]
See discussion in #1.

**Comment by charliermarsh** [comment]
\cc @jhossbach

**Comment by jhossbach** [comment]
> I think it should be fine to either: (1) let Ruff handle the pyproject.toml, and only pass CLI arguments that come directly from the LSP config (which could include config, allowing users to override); or (2) keep the current logic of letting the LSP find the pyproject.toml, pass it in as --config if the user hasn't provided a config override in the LSP settings.

I'd rather go with (1), it feels cleaner to let `ruff` handle the project-wide settings.
What do you think should be the configuration hierarchy for the LSP? If we start pylsp with e.g. the line-length to be 100 and work in different projects
Shouldn't the configuration hierarchy be project config > pylsp config? Say e.g. you disagree with the default line length of 88, so instead you configure your lsp via neovim to be 100 by default. If you now work in a project with a `pyproject.toml`, you would expect the LSP to use the configuration there instead, shouldn't it?

We could add some logic to use the user-configured options only if the `pyproject.toml` file doesn't contain this option

**Comment by charliermarsh** [comment]
Yeah I think you're right that project configuration should take precedence. I don't really have a great answer for how we should enable "defaults" in those other cases. 🤔

**Comment by jhossbach** [comment]
This should work:
```python
for key, value in toml_config.items():
    if key in [
        "exclude",
        "ignore",
        "line-length",
        "per-file-ignore",
        "select",
    ]:
        settings[key] = value
```
It will skip any entries in the `pyproject.toml` that are not in the list. We can extend this list if we want, but additional arguments in the toml file are used automatically by ruff anyway so unless someone wants to have more configurability from within pylsp I don't think this is necessary.

**Comment by charliermarsh** [comment]
Ruff is likely to support extending pyproject files (i.e., you could point to another pyproject file, and it’ll automatically merge in its settings). Which could make this hard to maintain, since you’d miss extended properties (or have to resolve the extension).

I think the safest thing to do would be: look for a pyproject.toml in all ancestor directories of the file. If we find one, don’t apply any of the LSP settings as command-line arguments (defer to Ruff). If we don’t, then apply the LSP settings as command-line arguments. What do you think?

**Comment by jhossbach** [comment]
I think this makes sense. In case I was working in a project with some configuration for ruff, I would expect that the default for ruff should still apply even if the option is not specified, so even if e.g. line-length was not explicitly set to 88 it would still apply within the project. I will create a PR for this.

**Comment by charliermarsh** [comment]
Awesome, happy to review!
