### ISSUE TITLE
Expose CodeAction "Disable for this line" for non-autofixable errors

### ISSUE THREAD

**Issue by magnuslarsen** [python-lsp/python-lsp-ruff#31]
Currently the CodeAction "Disable for this line" is only present if the error is flagged as autofix-able, but I'd like to have it for non-autofixable errors too.

It's a very minor convenience boost :-)

Thanks for a great plugin!
Magnus

**Comment by jhossbach** [comment]
I have added this feature in #35, can you pull and test this feature @magnuslarsen ?

**Comment by magnuslarsen** [comment]
I can confirm that is works - thanks you so much!

**Comment by jhossbach** [comment]
Great, I will merge and publish this in the upcoming release after #36 is solved!
