### ISSUE TITLE
test failure at last commits

### ISSUE THREAD

**Issue by Shane-XB-Qian** [python-lsp/python-lsp-ruff#39]
FAILED tests/test_code_actions.py::test_ruff_code_actions - ValueError: Position.character should be in range [0:2147483647], but was -1.
FAILED tests/test_code_actions.py::test_import_action - ValueError: Position.character should be in range [0:2147483647], but was -1.

tests/test_code_actions.py:78: 
tests/test_code_actions.py:103:

**Comment by Shane-XB-Qian** [comment]
> which version of `ruff` are you using?

v0.0.260

and a bit different with ver in ci : Python 3.10.6

**Comment by jhossbach** [comment]
I can reproduce the issue with `ruff` up to `v0.0.266`. Updating the package dependency to `v.0.0.267`. Thanks for the report!
