### ISSUE TITLE
Organize imports via code actions not working as expected

### ISSUE THREAD

**Issue by fast-90** [python-lsp/python-lsp-ruff#42]
When I try to "Organize imports" via code actions, I observe the following unexpected behaviour:

Before organizing imports:
![image](https://github.com/python-lsp/python-lsp-ruff/assets/76515405/62cd0ffc-6fff-46d2-8e4f-1ae2934184de)

After organizing import with python-lsp-ruff:
![image](https://github.com/python-lsp/python-lsp-ruff/assets/76515405/07f8e44a-d868-4a5a-9258-4980ee2ae98a)

Expected behaviour (below screenshot is obtained by using code actions with `ruff-lsp`):
![image](https://github.com/python-lsp/python-lsp-ruff/assets/76515405/e15ba22e-3e78-4b86-b44e-7a85934c49a2)

As you can see, a random `i` is inserted at the beginning, and the `c` from the `class` statement disappeared.

Performing the code action with `ruff-lsp` and running `ruff --fix file.py --extendSelect "I"` on the command line provide the expected result.

For reference, I am on WSL Ubuntu using Emacs (29) with `eglot`.

Not sure if this an issue something with Emacs/eglot or my setup, but as I don't have the issue with `ruff-lsp` I thought it might be worth checking here if anyone else has the same issue?

**Comment by jhossbach** [comment]
This issue should be fixed in the latest version of ´python-lsp-ruff`, can you update and check again?

**Comment by fast-90** [comment]
> This issue should be fixed in the latest version of `python-lsp-ruff` (or v1.5.0), can you update and check again?

Ah should have checked for recent updates! I can confirm I no longer have this issue. Thanks for the swift reply, and thanks for this awesome tool :)

**Comment by jhossbach** [comment]
No problem:)
