### ISSUE TITLE
lsp_format_on_save deleting entire file contents

### ISSUE THREAD

**Issue by staticf0x** [python-lsp/python-lsp-ruff#49]
When hitting ctrl+s to save a file, the LSP action to format a file is invoked. I found the ruff plugin to be the cause, here's the log file from python-lsp-server:

```
2023-10-18 08:41:40,113 CEST - ERROR - pylsp_ruff.plugin - Error running ruff: error: unexpected argument '--format' found

  tip: to pass '--format' as a value, use '-- --format'

Usage: ruff check <--verbose|--quiet|--silent> [FILES]...

For more information, try '--help'.
```

Seems like this option is deprecated in 0.1.0: https://github.com/astral-sh/ruff/pull/7984

**Comment by staticf0x** [comment]
My sublime text was using `ruff` from `.cache/sublime-text/Package Storage/LSP-pylsp/bin/` which is already on 0.1.0 thanks to sublime automatically updating packages. I had to manually set `pylsp.plugins.ruff.executable` to `~/.local/bin/ruff` which is on 0.0.292.

**Comment by jhossbach** [comment]
Yes, this is an issue with the latest ruff version, I will releqse a new version later today (see #48)

**Comment by staticf0x** [comment]
Great, thanks!

**Comment by staticf0x** [comment]
Although one thing I don't know if the PR fixes is: why does it attempt to format the file even when `pylsp.plugins.ruff.format` is `[]`? And why does it delete the file contents when the format fails?

**Comment by jhossbach** [comment]
The LSP receives a signal asking for formatting on the current file, but because of this error ruff will return this empty array, which the editor interprets as an empty file (as it should)
The return value usually contains the complete contents of the file, this is specified in the LSP specs as far as I know

**Comment by znd4** [comment]
@jhossbach  , if this plugin is currently using the first `ruff` on `PATH`, would it be possible to switch to `[sys.executable, "-m", "ruff", ...]`?

restatement: is the `ruff` version pin in `pyproject.toml` doing its job?

**Comment by jhossbach** [comment]
I need to check if `sys.executable` respects being called in an environment, but we can certainly do this. I don't see a problem though with the versioning, can you give an explicit example of it not working as intended? Make sure that the client calls the version `pylsp` from the correct virtual environment and that `ruff` with the correct version exists in that environment, otherwise there will be issues.

**Comment by znd4** [comment]
I'm not sure how reproducible this will be on other environments (although it might not be too hard to replicate in a Dockerfile, especially if there's a `pipx` - ready image), but currently I'm running into this after

```
pipx install --force "ruff>=0.1"
````

And it goes away after

 ```
 pipx install --force "ruff<0.1"
```

`pylsp --version` is `pylsp v1.8.2`

And yeah, I can try this out in a PR, although I'm not sure how much behavior varies across all of the downstream environments -- I'd hope that testing in a CPython `python -m venv` environment would be sufficient, but it's possible that different python distributions (e.g. circuitpython) or project tools (pdm, poetry, etc.) might behave differently. 

Based on personal anecdotal evidence, I haven't run into issues with `sys.executable` in the past, but there are a lot of environments I haven't worked in yet (embedded, WASM, etc.)

**Comment by jhossbach** [comment]
Hmm I see, I think this is related to `pipx` exposing the binaries to `~/.local/bin`.
I will create a new issue.

**Comment by staticf0x** [comment]
By the way, Sublime Text plugin does something similar, it prepends `PATH` with `.cache/sublime-text/Package Storage/LSP-pylsp/lib/python3.11` (or something along the way) so it avoids system paths or in my case `~/.local/lib/...`. The only way to use `ruff` from my `~/.local/bin` is to set `pylsp.plugins.ruff.executable` to a absolute path to the correct one.
