### ISSUE TITLE
Syntax errors not being shown when `select` is present in pyproject.toml

### ISSUE THREAD

**Issue by minusf** [python-lsp/python-lsp-ruff#67]
Hello, giving this a go, and i am running into this strange situation where Syntax errors stop being shown if the `pyproject.toml` file contains a `select = ` line.

without:
```
E class CustomFilter(PythonFilter):)))     ■■ SyntaxError: Unexpected token ')'
      ignore_dirs = ["__pycache__"]
```

with:
```
  class CustomFilter(PythonFilter):)))
      ignore_dirs = ["__pycache__"]
```

command line version works with the config file, so it's not a typo issue.

configuration is recommended lspconfig and
```
local lspconfig = require('lspconfig')
lspconfig.pylsp.setup {
  plugins = {
    ruff = {
      enabled = true,
    },
  }
}
```

`extendSelect` also doesn't seem to work.

**Comment by minusf** [comment]
doh. this was my mistake. `"E"` was missing from select. sorry for the noise

**Comment by jhossbach** [comment]
Glad it resolved itself.
