### ISSUE TITLE
fixall should consider range

### ISSUE THREAD

**Issue by Shane-XB-Qian** [python-lsp/python-lsp-ruff#71]
'fix all' of code action should consider the range, 
the statement in `def pylsp_code_actions(` :
```python
    range : Dict
        Range argument given by pylsp. Not used here.
```
should be not true, this range i guess should be used later in `checks_with_fixes` to filter fixes only in this range.
otherwise 'fix all' probably in the action list all the time, but that actually maybe would get action nothing from it.

**Comment by jhossbach** [comment]
I'm not sure what kind of range the 'Fix all' action should take, wouldn't you expect it to explicitly go through the whole document instead of only a range?

**Comment by Shane-XB-Qian** [comment]
> I'm not sure what kind of range the 'Fix all' action should take, wouldn't you expect it to explicitly go through the whole document instead of only a range?

as i know generally most lsp server no 'fix all' such thing, but 'all' is about 'range', if 'selected' is different, then 'all' is different.
// at least for now, 
// 1. that 'fix all' perhaps actually would do nothing, but stayed in action list still.
// 2. for now, this lsp server did not support code action in range which unlike others.

-- 
shane.xb.qian

**Comment by jhossbach** [comment]
You mentioned that other language servers also include ranges in fix all actions, but I couldn't find any that check in the range only (i.e. [ruff-lsp](https://github.com/astral-sh/ruff-lsp/blob/94577abee37a98c2b571a9ac4f7ec1f167d72dd2/ruff_lsp/server.py#L859C5-L890)).
Otherwise I would be opposed to this, since the "Fix all" action is supposed to just go through the document and apply any easy applicable fixes without any user input required.

**Comment by Shane-XB-Qian** [comment]
> You mentioned that other language servers also include ranges in fix all actions, but I couldn't find any that check in the range only (i.e. [ruff-lsp](https://github.com/astral-sh/ruff-lsp/blob/94577abee37a98c2b571a9ac4f7ec1f167d72dd2/ruff_lsp/server.py#L859C5-L890)).

i did not mean 'ruff' or 'python' lsp, this one is the only one i can find had 'fix all' action in the list.

> Otherwise I would be opposed to this, since the "Fix all" action is supposed to just go through the document and apply any easy applicable fixes without any user input required.

ok, understand, besides as i said in #72, i have no idea why that 2 issues happened, not sure if was me made it or was existed, but current 'fix all' would cover it.

-- 
shane.xb.qian
