### ISSUE TITLE
ruff command line is missing subcommand when specifying executable in config

### ISSUE THREAD

**Issue by dfn-certling** [python-lsp/python-lsp-ruff#74]
If the executable is specified in the LSP config, the command line to run ruff is constructed and executed in 
https://github.com/python-lsp/python-lsp-ruff/blob/c0182658f727b26a9d43d156005ee2bd2252e9c4/pylsp_ruff/plugin.py#L517-L519

This call is missing the subcommand to actually execute with ruff. Compare to the call constructed for the fallback usage of the Python module in
https://github.com/python-lsp/python-lsp-ruff/blob/c0182658f727b26a9d43d156005ee2bd2252e9c4/pylsp_ruff/plugin.py#L527-L529

which includes `str(subcommand)`.

Without the subcommand ruff seems to fallback to linting and does nothing to the buffer when trying to format through the LSP. Just adding `str(subcommand)` to the executable command fixes this for me.

**Comment by jhossbach** [comment]
Hey @dfn-certling, thanks for the bug report! I will push a bugfix release today.
