### ISSUE TITLE
Ruff stops working when I indicate a config file in CocConfig

### ISSUE THREAD

**Issue by lemerchand** [python-lsp/python-lsp-ruff#76]
Hi there. I am wondering what I am doing wrong here. I have several rules I like to change for nearly all my projects, like line-length, single vs double quotes, etc. I have made a `.ruff.toml` in my dotfiles folder and in my CocConfig I added `"pylsp.plugins.ruff.config": "~/dotfiles/ruff.toml"`  to link to it for use.

I can see linting errors when I remove the line, and when I add it they go away. Am I doing this wrong? 

If it matters I'm using VIm, not NeoVim. I also have the following pylsp settings:

```
{
	"pylsp.enable": true,
	"pylsp.builtin.enableInstallPythonLspRuff": true,
	"pylsp.plugins.pycodestyle.enabled": false,
	"pylsp.plugins.pyflakes.enabled": false,
	"pylsp.plugins.mccabe.enabled": false,
	"pylsp.plugins.ruff.format": [
		"I"
	],
	"pylsp.plugins.ruff.config": "~/dotfiles/ruff.toml"
}

```

**Comment by jhossbach** [comment]
Do you have ruff config files in your projects or a ruff section in the `pyproject.toml` file?
`python-lsp-ruff` ignores this config file if it finds an existing configuration in the project directory.
If thats not the case, please provide the lsp logs by setting the `pylsp.plugins.ruff.config` to something like `<path_to_pylsp> -vvv --log-file /tmp/lsp.log`

**Comment by lemerchand** [comment]
No, I do not have any ruff config files in the project dir, nor is there anything about ruff in the `pyproject.toml`

Unless I'm mistaken about something, setting `"pylsp.plugins.ruff.config": "- /usr/bin/pylsp -vvv --log-file /tmp/lsp.log"` does not result in a lsp.log in /tmp after `CocRestart` or even a hard reset on Vim.

**Comment by jhossbach** [comment]
Sorry, I meant `pylsp.plugins.ruff.executable`, please enable debugging with that and post the output

**Comment by lemerchand** [comment]
No worries. Okay so I have tied both the path to pylsp and the path to ruff under `"pylsp.plugins.ruff.executable":` as well as with and without the line pointing to me config in my dotfiles added. Neither produce a log in /tmp.  I have verified the paths to the executables using `which` so we know they are installed. Just for the sake of completeness here is the cocconfig lines I tried:

```
	"pylsp.plugins.ruff.executable": "~/.local/bin/ruff -vvv --log-file /tmp/lsp.log"

```

as well as

```
	"pylsp.plugins.ruff.executable": "/usr/bin/pylsp -vvv --log-file /tmp/lsp.log"

```

Any new ideas? Thanks for taking the time to help me out!

**Comment by jhossbach** [comment]
Hmm, you might need to give each argument as an item of a list, something like `["pylsp", "-vvv", "--log-file", "/tmp/lsp.log"]`, check whether that is valid vimscript syntax though

**Comment by lemerchand** [comment]
This is in my coc-settings so it's json, not vimscript. Good idea with passing a list of strings--I forgot that there are times where that is necessary--though though this also does not give me a log. My json linter also gives me a error saying it expects a single string. 

I'm sorry this is lingering so long. Any other ideas? If not then maybe I'll just make a cp of my ruff.toml to put in each project.

**Comment by jhossbach** [comment]
I am not sure why pylsp does not print debugging messages, so here are some ideas to play with:
 - check out if choosing a different directory for the log file works
 - double-check that the correct python executable is used (`pylsp.builtin.pythonPath` could e.g. be explicitly set in the `coc-settings.json`
 - maybe check whether you are running in a python environment with an older pylsp/pylsp-ruff/ruff version (did you e.g. set `g:python3_host_prog`?)

If that doesn't help, you could also try with a minimal neovim config and see if you can reproduce this issue.
It might also help to post over at `coc-pylsp` and ask for help.

**Comment by lemerchand** [comment]
You can close the issue....it's pretty embarrassing but I solved it :joy: 

I became suspicious that the problem was with ruff and not pylsp, so I ran it via the command line and found out I  had accidentally set tabs to 'spaces' not 'space' and it was causing a parsing error. Sorry for wasting so much of your time, but I really appreciate the effort you went through to help me out!

**Comment by jhossbach** [comment]
Great to hear it resolved itself!
