### ISSUE TITLE
Does this project really use black?

### ISSUE THREAD

**Issue by doolio** [python-lsp/python-lsp-ruff#77]
https://github.com/python-lsp/python-lsp-ruff/blob/f5bcc658c533730e35f8cfc98072907f1f8e8f00/pyproject.toml#L36-L38

**Comment by jhossbach** [comment]
Yes, `black` is run as part of the CI, which runs pre-commit:

https://github.com/python-lsp/python-lsp-ruff/blob/2dd45687bf367bb48389f695c043eb7bb4132955/.github/workflows/python.yml#L22-L23

... and in the pre-commit config it runs specifies black:
https://github.com/python-lsp/python-lsp-ruff/blob/2dd45687bf367bb48389f695c043eb7bb4132955/.pre-commit-config.yaml#L2-L5
