### ISSUE TITLE
Allow disabling formatter

### ISSUE THREAD

**Issue by AtomToast** [python-lsp/python-lsp-ruff#83]
As someone only needing the linting part of ruff, I'd like to be able to disable the formatter, which conflicts with the formatter I do use.

I spent the better part of the day trying to figure out why black always broke the formatting when running inside of my editor but not when running from our pre-commit hook or manually in the terminal... Now I finally figured out that it was actually this plugin having formatting enabled by default.
Ruff formatting is not 100% compatible with black, which basically stops me from using this plugin entirely in my workflow. Which sucks because I do actually want the linting part of ruff.

Otherwise I guess I'll need to setup another language server for which I can then entirely disable document formatting

**Comment by jhossbach** [comment]
Looking into it.

**Comment by jhossbach** [comment]
Can you checkout https://github.com/python-lsp/python-lsp-ruff/tree/fix_%2383 and see if that resolves your issue? I tried locally with neovim and it seems to work.

**Comment by AtomToast** [comment]
That resolves it for me 👍

**Comment by AtomToast** [comment]
Any chance of getting this into a pr?

**Comment by jhossbach** [comment]
Certainly, but I want to check if returning `None` is valid as a formatting response before merging.

**Comment by jhossbach** [comment]
I think we are good to go:
https://github.com/microsoft/lsprotocol/blob/610626a4d32faee96302f5db385f14fa4bc1de95/packages/python/lsprotocol/types.py#L10805
