### ISSUE TITLE
How is python-lsp-ruff updated in Neovim?

### ISSUE THREAD

**Issue by PhilippFeO** [python-lsp/python-lsp-ruff#88]
I use python-lsp-server in Neovim and also have python-lsp-ruff installed. I wonder, how I receive updates of Ruff because it used as a plugin and Mason doesn't know explicitly about python-lsp-ruff.

**Comment by jhossbach** [comment]
Neither python-lsp-server, nor python-lsp-ruff and ruff itself are updated by neovim, you will have to do that manually. If mason has this kind of update feature for python-lsp-server, maybe it is possible to add on-update hooks or callbacks one could manually define?

**Comment by PhilippFeO** [comment]
Okay, I kinda expected this answer. Sounds like having a current version of ruff implies using ruff-lsp directly when I want to avoid tweaking it as described.. In case I'll stay with python-lsp-ruff, I will post my solution here.

PS: I'm a bit impressed that you maintain this repo as student!
