### ISSUE TITLE
Question: What is the difference between using python-lsp-ruff and using ruff-lsp?

### ISSUE THREAD

**Issue by NeilGirdhar** [python-lsp/python-lsp-ruff#89]
I posted here, but just want to crosspost in case you are able to answer it better https://github.com/python-lsp/python-lsp-server/discussions/553

**Comment by NeilGirdhar** [comment]
Thank you!



> `python-lsp-server` also provides access to other features, such as go-to, object renaming etc, while `ruff-lsp` can 'only' do what `ruff` itself provides.

The Pyright LSP provides those things as well, right?  If I'm using PyRight for renaming and go-to, would I want Ruff as well?

**Comment by jhossbach** [comment]
Yes, pyright also allows for renaming etc. In this case I would go for `pyright` (type checking, goto) + `ruff-lsp` (linting, formatting)

**Comment by NeilGirdhar** [comment]
Thank you!

**Comment by Shane-XB-Qian** [comment]
supposed you meant pylance?
didn't use ruff-lsp but I supposed better idea was enhanced something which let this have better usage experience than that. :sweet_smile:

--
shane.xb.qian

**Comment by NeilGirdhar** [comment]
@Shane-XB-Qian I use NeoVim with the language servers: `pyright` and `ruff_lsp`.
